version: "3.9"
services:
  postgres-devsu-db:
    image: postgres:15
    container_name: postgres-devsu-bd
    build:
      context: ./modulo-comun/comun-acceso-datos
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - red-devsu-app
    restart: always


volumes:
  postgres-data:

networks:
  red-devsu-app:
    driver: bridge
