FROM postgres:15

# Configura las variables de entorno para PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Exponer el puerto predeterminado de PostgreSQL
EXPOSE 5432
