server:
  port: 8181
  error:
    whitelabel:
      enabled: false

logging:
  level:
    ec.banca.app: DEBUG

spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql
  mvc:
    view:
      prefix:
      suffix:
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres-banca:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

