server:
  port: 8182
  error:
    whitelabel:
      enabled: false

logging:
  level:
    ec.banca.app: DEBUG

spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
    consumer:
      group-id: "grupo-clientes"
      auto-offset-reset: earliest
    producer:
      acks: all
    admin:
      auto-create: true
  mvc:
    view:
      prefix:
      suffix:
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

